{
"appPort": 8080,
"client": "postgresql",
"connection.database": "my_db",
"connection.user":     "username",
"connection.password": "password"
"pool.min": 2,
"pool.max": 10
"migrations.tableName": "knex_migrations"
"cap_limit": 0
}